Pod creation fails on open shift 4.5.3 with isito 1.4.6
istio/cni pull request #278
Opened 2020-03-25 00:17 UTC by jacob-delgado

Fixes https://github.com/istio/istio/issues/22449

2020-03-25 00:18 UTC, jacob-delgado commented
Once we've decided on the best course of action for 1.4, I'll fix this in 1.5 and master.

2020-03-25 00:19 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_cni_release-1.4 | 125e49663cdfc9b8627fadcd281c6f11dca9e025 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_cni/278/lint_cni_release-1.4/19) | `/test lint_cni_release-1.4`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-10 15:32 UTC, nrjpoddar commented
@jacob-delgado can we get this merged?

2020-04-10 18:54 UTC, jacob-delgado commented
cc @brian-avery @rlenglet 

Can you please review this? I'll ping the release managers when I get a thumbs up.

2020-04-15 15:56 UTC, brian-avery commented
Looks reasonable to me, but I'm not a CNI expert.

2020-04-15 15:57 UTC, nrjpoddar commented
> Looks reasonable to me, but I'm not a CNI expert.

Do you know who's? This is breaking on of our customers and we are currently patching it in private. Much easier for us to upstream these fixes. Thanks!

2020-04-15 16:06 UTC, brian-avery commented
@luksa wrote our CNI content for OpenShift Service Mesh. I've asked him to take a look.

2020-04-15 16:07 UTC, howardjohn commented on deployments/kubernetes/install/helm/istio-cni/values.yaml
> +kubernetesCNIConfDir: /etc/kubernetes/cni/net.d
The PR is about openshift but looks like this impacts everyone. What is the impact of this change for GKE/kind/EKS/others?

2020-04-15 16:36 UTC, jwendell commented
I fixed this on master a couple of months ago and it was backported to 1.5.

The instructions are here: https://istio.io/docs/setup/additional-setup/cni/#hosted-kubernetes-settings

So, would it make sense to backport the same fix to 1.4?

2020-04-15 16:49 UTC, luksa commented
@jwendell +1

2020-04-15 17:22 UTC, rlenglet commented
@jwendell +1

2020-04-15 18:58 UTC, lambdai requested changes
Can you guard the usage of k8s-cni-net-dir?  in both
1. mount in spec
2. install-cni, check readiness only if the it exist.

2020-04-15 18:58 UTC, lambdai commented on deployments/kubernetes/install/helm/istio-cni/templates/istio-cni.yaml
> +            - mountPath: /host/etc/kubernetes/cni/net.d
I checked the my k8s cluster: The k8s node (aka host) has not `/etc/kubernetes/cni/net.d`. 
It will break the gke

2020-04-15 23:43 UTC, jacob-delgado commented
> I fixed this on master a couple of months ago and it was backported to 1.5.
> 
> The instructions are here: [istio.io/docs/setup/additional-setup/cni/#hosted-kubernetes-settings](https://istio.io/docs/setup/additional-setup/cni/#hosted-kubernetes-settings)
> 
> So, would it make sense to backport the same fix to 1.4?

I take it this is the issue https://github.com/istio/cni/pull/237? A uniformed approach across all supported versions would be better than the approach in this PR.

2020-04-16 03:17 UTC, mandarjog commented
it is concerning that none of the tests failed.
For every supported platform vendors should add tests.
Google team will do it for gke and Kind is not it.

2020-04-16 19:19 UTC, jacob-delgado commented
> Can you guard the usage of k8s-cni-net-dir? in both
> 
> 1. mount in spec
> 2. install-cni, check readiness only if the it exist.

I reverted my changes and did a manual backport of https://github.com/istio/cni/pull/237

One discrepancy is in the install-cni.sh script found here https://github.com/istio/cni/pull/237/files#diff-a1fbe10058a1077a440d75c2abf5f1e1R93

2020-04-16 19:22 UTC, nrjpoddar commented
@jwendell PTAL, this has your PR changes backported.

@mandarjog @lambdai can you do the verification on your platform?

2020-04-16 19:31 UTC, nrjpoddar commented
@jacob-delgado this PR needs corresponding changes in other repos:

https://github.com/istio/istio/pull/20708
 and doc changes for 1.4

2020-04-16 20:05 UTC, lambdai approved these changes
Thank you @jacob-delgado 
LGTM

2020-04-16 20:09 UTC, lambdai commented
I add do-not-merge label so that @jwendell can do the final review. Please you can remove the label then.

2020-04-16 20:53 UTC, jwendell approved these changes
LGTM

I'll wait for the changes in operator repo for istioctl and instructions on how to install (docs) so that I can do a manual test.

2020-04-17 03:47 UTC, ericvn commented
I'll merge this and the operator change, https://github.com/istio/operator/pull/771, in preparation for a overall build in the morning.

2020-04-17 03:48 UTC, ericvn approved these changes

2020-04-17 03:49 UTC, merged

2020-04-17 14:39 UTC, ericvn commented
https://github.com/istio/istio.io/pull/7095 is the Doc PR. 

One issue I noted in their and confirmed with @frankbu this morning is that the istio.io archive docs (which includes 1.4) are frozen and can't be updated. He did say that if we have to fix something in an old release, we can explain the doc is wrong and the needed change in the release notes for the point release.

Does that invalidate this solution? Or is the release notes sufficient? Looking at the doc PR changes, it seems to imply the docs are broken as they are now (oc has -n instead of a : ) in addition to the new install section. Maybe the user will look at the current 1.5 docs which I believe have the same/correct items.